version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
           
    steps:
      - checkout
      - run: 
          name: Set .env file
          command: |
              echo "AUTH0_DOMAIN=$auth0_domain" >> .env
              echo "API_IDENTIFIER=$api_identifier" >> .env
          
      - run: 
           name: background server
           command: sh exec.sh
           background: true
      
      - run: sleep 20
      
      - run:
          name: Clone script test
          command: git clone -b refactor-for-integration https://github.com/rafanog/auth0-test-api-quickstarts.git test
          #command: git clone http://github.com/rafanog/test-script.git test
                      
      - run: 
          name: Prepare environment variables for test
          command: |
            cd test
            echo "AUTH0_DOMAIN=$auth0_domain" >> .env
            echo "API_IDENTIFIER=$api_identifier" >> .env
            echo "AUTH0_CLIENT_ID_1=$client_id_scopes_none" >> .env
            echo "AUTH0_CLIENT_SECRET_1=$client_secret_scopes_none" >> .env
            echo "AUTH0_CLIENT_ID_2=$client_id_scopes_read" >> .env
            echo "AUTH0_CLIENT_SECRET_2=$client_secret_scopes_read" >> .env
            echo "AUTH0_CLIENT_ID_3=$client_id_scopes_write" >> .env
            echo "AUTH0_CLIENT_SECRET_3=$client_secret_scopes_write" >> .env
            echo "AUTH0_CLIENT_ID_4=$client_id_scopes_readwrite" >> .env
            echo "AUTH0_CLIENT_SECRET_4=$client_secret_scopes_readwrite" >> .env
            echo "API_URL=http://localhost:3010" >> .env
      
      - run:
          name: Install test script dependency
          command: cd test && npm install
          #command: cd test && npm install && npm install asyncawait
      - run:
          name: Test
          command: cd test && npm test
workflows:
  version: 2
  build:
    jobs:
      - build
      - test

